import type { Metadata } from 'next';

import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { withAuth } from '@/lib/withAuth';

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
};

async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await withAuth();

  return (
    <SidebarProvider defaultOpen={false}>
      <AppSidebar />
      <main className={'mx-2 w-full'}>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
  );
}

export default DashboardLayout;
